database_dsn:
    phptype: mysql
    username: dragoon_db 
    password: password 
    database: dragoon_user 
    hostspec: localhost

name: Natilie (Sample) 
uid: 1001
gid: 1001
home_dir: /usr/share/dragoond
log_dir: /var/log/dragoon_logs
module_dir: /use/share/dragoond/modules
debug: 0 

default_modules:
    - datasource_fetcher
    - jabber_frontend 
    - rss_reader
